ChestItems:
  - STONE
  - DIAMOND_SWORD
  - DIAMOND_AXE
  - IRON_SWORD
  - BOW
  - ARROW
  - DIAMOND_HELMET
  - DIAMOND_CHESTPLATE
  - DIAMOND_LEGGINGS
  - DIAMOND_BOOTS
  - IRON_HELMET
  - IRON_CHESTPLATE
  - IRON_LEGGINGS
  - IRON_BOOTS
  - ENDER_PEARL
  - FISHING_ROD
  - DIAMOND_PICKAXE
  - GOLDEN_APPLE